config/routes.rb
Rails.application.routes.draw do
  root 'trips#index'
  resources :trips
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/nest.rb
class Nest < ApplicationRecord
  belongs_to :trip,inverse_of: :nests
  has_many :schejules, inverse_of: :nest
  accepts_nested_attributes_for :schejules, allow_destroy: true
end

app/models/schejule.rb
class Schejule < ApplicationRecord
    belongs_to :nest,inverse_of: :schejules
end

app/models/trip.rb
class Trip < ApplicationRecord
    has_many_attached :images
    has_many :nests, inverse_of: :trip
    accepts_nested_attributes_for :nests, allow_destroy: true, update_only: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/trips_controller.rb
class TripsController < ApplicationController
  before_action :set_trip, only: [:show, :edit, :update, :destroy]

  # GET /trips
  # GET /trips.json
  def index
    @trips = Trip.all
  end

  # GET /trips/1
  # GET /trips/1.json
  def show
  end

  # GET /trips/new
  def new
    @trip = Trip.new
    #@nest = @trip.nests.build
    #@nest.schejules.build
  end

  # GET /trips/1/edit
  def edit
  end

  # POST /trips
  # POST /trips.json
  def create
    @trip = Trip.new(trip_params)

    respond_to do |format|
      if @trip.save
        format.html { redirect_to @trip, notice: 'Trip was successfully created.' }
        format.json { render :show, status: :created, location: @trip }
      else
        format.html { render :new }
        format.json { render json: @trip.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /trips/1
  # PATCH/PUT /trips/1.json
  def update
    respond_to do |format|
      if @trip.update(trip_params)
        format.html { redirect_to @trip, notice: 'Trip was successfully updated.' }
        format.json { render :show, status: :ok, location: @trip }
      else
        format.html { render :edit }
        format.json { render json: @trip.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /trips/1
  # DELETE /trips/1.json
  def destroy
    @trip.destroy
    respond_to do |format|
      format.html { redirect_to trips_url, notice: 'Trip was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_trip
      @trip = Trip.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def trip_params
      params.require(:trip).permit(:triptitle, :membar, :startdate, :enddate, :place, :bhotel,
        :bflight, :bfood, :date, :starttime, :endtime,
        nests_attributes: [:id, :breakfast,:lunch,:dinner,:hotel,:date,:_destroy,
        schejules_attributes: [:id, :time, :action, :content,:remark, :_destroy]],images: [])
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
    # This method creates a link with `data-id` `data-fields` attributes. These attributes are used to create new instances of the nested fields through Javascript.
    def link_to_add_fields(name, f, association)

        # Takes an object (@person) and creates a new instance of its associated model (:addresses)
        new_object = f.object.send(association).klass.new

        # Saves the unique ID of the object into a variable. 
        id = new_object.object_id

        # https://api.rubyonrails.org/ fields_for(record_name, record_object = nil, fields_options = {}, &block) 
        fields = f.fields_for(association, new_object, child_index: id) do |builder|
            render(association.to_s.singularize + "_fields", f: builder)
        end

        # This renders a simple link, but passes information into `data` attributes.
        link_to(name, '#', class: "add_fields", data: {id: id, fields: fields.gsub("\n", "")})
    end
end

app/helpers/trips_helper.rb
module TripsHelper
end

app/views/layouts/application.html.slim
doctype html
html
  head
    title
      | Sample
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_pack_tag 'application','data-turbolinks-track': 'reload'
  body
    header
      = react_component("navbar/Appbar")
    main.uk-container
      = yield
    footer

app/views/trips/_f-hschejule.html.slim
thead
    tr
        th
            | 時間
        th
            | 行動
        th
            | 内容
        th
            | 備考

app/views/trips/_form.html.slim
f.uk-f-stacked
= form_with(model: trip, local: true)  do |f|
  - if trip.errors.any?
    #error_explanation
      h2
        = pluralize(trip.errors.count, "error")
        |  prohibited this trip from being saved:
      ul
        - trip.errors.full_messages.each do |message|
          li
            = message
  .uk-section.uk-section-default
  .uk-container
    h1.uk-text-bold.uk-margin-bottom.uk-text-center
      = f.label :triptitle
      = f.text_field :triptitle
    h2.uk-heading-divider
      | 旅行の概要
    label.uk-form-label
      = f.label :member
    .uk-form-controls
      = f.text_field :membar, {class: "uk-input uk-form-width-medium"}
    label.uk-form-label
      = f.label :startdate
    .uk-form-controls
      = f.text_field :startdate,data: { behavior: "flatpickr-range" }
    #total-price
    /= react_component("Datepicker", { trip: @trip })
    #totaldays
    label.uk-form-label
      = f.label :place
    .uk-form-controls
      = f.text_field :place, {class: "uk-input uk-form-width-medium"}
    label.uk-form-label
      | Budget
    p.uk-margin-bottom
      = react_component("Autocomp", { trip: @trip })
  .uk-container
    h2.uk-heading-divider.uk-margin-bottom
      | 詳細スケジュール
    /ul.uk-subnav.uk-subnav-pill uk-switcher=""
      li 
        a 1日目
      li 
        a 2日目
      li 
        a 3日目
    /ul.uk-switcher.uk-margin
      li
      li Hello again!
      li Bazinga!
  /.field
    = f.label :comment
    = f.text_area :comment
  #nests
    = f.fields_for :nests do |nest|
        = render 'nest_fields',f: nest
    .links
        = link_to_add_association "スケジュールを追加する",f,:nests,
              {:"data-association-insertion-method" => "append"}
  .uk-section.uk-section-muted
  .uk-container
    h2.uk-heading-divider
      || Photo
    = f.file_field :images, multiple: true
  .actions
    = f.submit

app/views/trips/_images.html.slim
div.uk-grid class="uk-child-width-1-3@m" uk-scrollspy="cls: uk-animation-fade; target: .uk-card; delay: 500; repeat: true"
    - @trip.images.each do |image|
      .uk-card.uk-card-default.uk-card-body
        = image_tag(image)

app/views/trips/_nest_fields.html.slim
.nested-fields
    .field
        p.uk-badge
            = f.index.to_i+1
            | 日目
    br
    .field
        p.uk-label.uk-label-success
            |グルメ
        p.uk-margin-bottom
            |　朝食：
            = f.text_field :breakfast
    .field
        p.uk-margin-bottom
            |　昼食：
            = f.text_field :lunch
    .field
        p.uk-margin-bottom
            |　夕食：
            = f.text_field :dinner
    .field
        span.uk-label.uk-label-success
            | ホテル:
        p.uk-margin-bottom
            = f.text_field :hotel
    .field
        span.uk-label.uk-label-success
            |タイムスケジュール
        #schejules
            table.uk-table.uk-table-small.uk-table-divider
                = render 'f-hschejule'
            = f.fields_for :schejules do |schejules|
                = render "schejule_fields", f: schejules
            .links
                = link_to_add_association "タイムスケジュールを追加する",f,:schejules
            = link_to_remove_association "スケジュールを削除する", f

app/views/trips/_s-schejule.html.slim
ul.uk-subnav.uk-subnav-pill uk-switcher=""
  - @trip.nests.each_with_index do |trip,i|
      li
        a.uk-margin-bottom
          = "#{(i + 1)}" + "日目"
ul.uk-switcher.uk-margin
  - @trip.nests.each_with_index do |trip,i|
    li
      p.uk-margin-bottom
          |　朝ごはん：
          = trip.breakfast
      p.uk-margin-bottom
          |　昼ごはん：
          = trip.lunch
      p.uk-margin-bottom
          |　夜ごはん：
          = trip.dinner
      span.uk-label.uk-label-success
          | ホテル:
      p.uk-margin-bottom
          = trip.hotel
      span.uk-label.uk-label-success
          |タイムスケジュール
      table.uk-table.uk-table-justify.uk-table-divider
        thead
          tr
            th.uk-width-small
              | 時間
            th.uk-width-small
              | 行動
            th 
              | 内容
            th 
              | 備考
        tbody
          - trip.schejules.each do |trip|
            tr
              td
                = trip.time
              td
                = trip.action
              td
                = trip.content
              td
                = trip.remark

app/views/trips/_s-thumbnail.html.slim
.uk-card.uk-card-default
    .uk-card-body
        h3.uk-card-title
            = @trip.triptitle
        p 長崎の潜伏キリシタン関連遺産をガイド付きで。“隠れキリシタン”に思いをはせる旅
        .uk-card-media-bottom
            = image_pack_tag 'light.jpg'

app/views/trips/_s-trip.html.slim
/span.uk-badge
    | メンバー
/p.uk-margin-bottom
    = @trip.membar
span.uk-badge.uk-margin-top
    = react_component("Box",name:"スケジュール")
p.uk-margin-bottom
    = @trip.startdate
#totaldays
span.uk-badge
    | 場所
p.uk-margin-bottom
    = @trip.place
span.uk-badge
    | 予算
p.uk-margin-bottom
    |　ホテル：
    = @trip.bhotel
p.uk-margin-bottom
    |　交通費：
    = @trip.bflight
p.uk-margin-bottom
    |　食費　：
    = @trip.bfood

app/views/trips/_schejule_fields.html.slim
table.uk-table.uk-table-small.uk-table-divider
    tbody.nested-fields
        tr
            = f.hidden_field :_destroy
            td
                = f.text_field :time,data: { behavior: "flatpickr-time"},class: ".un uk-input uk-form-width-small"
            td
                = f.select :action,['移動', '食事', '観光'], {include_blank: '行動'}, class: "uk-input uk-form-width-small"
            td
                = f.text_field :content, class: "uk-input uk-form-width-medium"
            td
                = f.text_field :remark,class: "uk-input uk-form-width-small"
            td
                = link_to_remove_association "削除", f

app/views/trips/edit.html.slim
h1
  | Editing Trip
= render 'form', trip: @trip
= link_to 'Show', @trip
|  | 
= link_to 'Back', trips_path

app/views/trips/index.html.slim
p#notice
  = notice
h1
  | Trips
table
  thead
    tr
      th
        | Triptitle
      th
        | Membar
      th
        | Startdate
      th
        | Enddate
      th
        | Place
      th
        | B-hotel
      th
        | B-flight
      th
        | B-food
      th
        | Date
      th
        | G-morning
      th
        | G-lunch
      th
        | G-dinner
      th
        | Hotelname
      th
        | Starttime
      th
        | Endtime
      th
        | Action
      th
        | Route
      th
        | Remarks
      th
        | Comment
      th[colspan="3"]
  tbody
    - @trips.each do |trip|
      tr
        td
          = trip.triptitle
        td
          = trip.membar
        td
          = trip.startdate
        td
          = trip.enddate
        td
          = trip.place
        td
          = trip.bhotel
        td
          = trip.bflight
        td
          = trip.bfood
        td
          = trip.date
        td
          = trip.gmorning
        td
          = trip.glunch
        td
          = trip.gdinner
        td
          = trip.hotelname
        td
          = trip.starttime
        td
          = trip.endtime
        td
          = trip.action
        td
          = trip.route
        td
          = trip.remarks
        td
          = trip.comment
        td
          = link_to 'Show', trip
        td
          = link_to 'Edit', edit_trip_path(trip)
        td
          = link_to 'Destroy', trip, method: :delete, data: { confirm: 'Are you sure?' }
br
= link_to 'New Trip', new_trip_path

app/views/trips/new.html.slim
h1
  | New Trip
= render 'form', trip: @trip
= link_to 'Back', trips_path

app/views/trips/show.html.slim
p#notice
  = notice
.uk-section.uk-section-default
  .uk-container
    /h1.uk-text-bold.uk-margin-bottom.uk-text-center
        = @trip.triptitle
    .uk-grid
      div class="uk-width-1-2@m"
        == render "s-thumbnail"
      div class="uk-width-1-2@m"
        == render "s-trip"
    // Tab 
    ul.uk-child-width-expand uk-tab=""
      li
        a href="#"
          | Schejule
      li
        a href="#"
          | Photo
      li
        a href="#"
          | Remarks
    // Tab-content
    ul.uk-switcher.uk-margin
      li.uk-section-xsmall.uk-background-default
        .uk-padding
          == render "s-schejule"
      li.uk-section-xsmall.uk-background-default
        .uk-padding
          == render 'trips/images'
      li.uk-section-xsmall.uk-background-default
        .uk-padding
          = @trip.comment
    //= react_component("App")
    = link_to 'Edit', edit_trip_path(@trip)
    |  | 
    = link_to 'Back', trips_path